/* This file is auto-generated by tool, DO NOT modify it manully. */

#ifndef CONFIG_BOARDIDS_H
#define CONFIG_BOARDIDS_H

#define BOARD_ID_U9501L_VA   136
#define BOARD_ID_U9501L_VB   8
#define BOARD_ID_U9501L_VC   24
#define BOARD_ID_U9501L_VD   40
#define BOARD_ID_U9501L_VE   56

#endif
